# Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
FROM registry.aifoundry.amd.com/rocm-manylinux228-rhel810:10.1.0a20260821
# Install ROCm Paddle wheel (AMD-AIOSS/hipSHIFT port/Paddle delivery)
COPY amd_paddlepaddle-*.whl /tmp/
RUN pip install /tmp/amd_paddlepaddle-*.whl
# Install PaddleRec deps (ROCm-compatible, no faiss-gpu)
COPY requirements-rocm.txt amd-constraints.txt /opt/paddlerec/
RUN pip install -r /opt/paddlerec/requirements-rocm.txt -c /opt/paddlerec/amd-constraints.txt
# Install PaddleRec
RUN pip install git+https://github.com/PaddlePaddle/PaddleRec.git@v2.1.0
ENV LD_LIBRARY_PATH=/opt/rocm/lib/llvm/lib:/opt/rocm/lib:$LD_LIBRARY_PATH
